# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

source 'https://github.com/CocoaPods/Specs.git' # 公共仓库地址
#source 'https://github.com/FQDEVER/FQ_AlertView.git'        #私有仓库地址

target 'FQ_AlertTipView' do
    #pod 'Masonry'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "11.0"
    end
  end
end
